using System.Runtime.InteropServices;

namespace EasyUniVPN;

/// <summary>
/// Installs a WH_KEYBOARD_LL hook to detect Ctrl+Alt+V globally.
///
/// Unlike RegisterHotKey (which fails when another app owns the combo) or
/// IMessageFilter (which depends on message routing to our hidden window),
/// a low-level keyboard hook is called by the kernel for every physical
/// keystroke, regardless of which application has focus or what privileges
/// the foreground process holds.
///
/// The hook is delivered on the installing thread via the message pump
/// (Application.Run() must be running on the same thread). The delegate is
/// stored in a field to prevent the GC from collecting it while the hook is
/// active - collecting the delegate causes an unrecoverable crash.
///
/// The callback is invoked directly from the hook proc on the UI thread.
/// It must return quickly - it should only do a fast check and spawn a
/// background STA thread for any heavy work (e.g. clipboard operations).
/// </summary>
internal sealed class HotkeyWindow : IDisposable
{
    private const int  WH_KEYBOARD_LL = 13;
    private const int  WM_KEYDOWN     = 0x0100;
    private const int  WM_SYSKEYDOWN  = 0x0104;
    private const uint LLMHF_INJECTED = 0x01;    // set on events generated by SendInput
    private const uint VK_CONTROL     = 0x11;
    private const uint VK_MENU        = 0x12;    // Alt
    private const uint VK_V           = 0x56;

    [StructLayout(LayoutKind.Sequential)]
    private struct KBDLLHOOKSTRUCT
    {
        public uint    vkCode;
        public uint    scanCode;
        public uint    flags;
        public uint    time;
        public UIntPtr dwExtraInfo;
    }

    private delegate IntPtr LowLevelKeyboardProc(int nCode, IntPtr wParam, IntPtr lParam);

    [DllImport("user32.dll",   SetLastError = true)]
    private static extern IntPtr SetWindowsHookEx(int idHook, LowLevelKeyboardProc lpfn, IntPtr hMod, uint dwThreadId);

    [DllImport("user32.dll",   SetLastError = true)]
    private static extern bool UnhookWindowsHookEx(IntPtr hhk);

    [DllImport("user32.dll")]
    private static extern IntPtr CallNextHookEx(IntPtr hhk, int nCode, IntPtr wParam, IntPtr lParam);

    [DllImport("user32.dll")]
    private static extern short GetAsyncKeyState(int vKey);

    [DllImport("kernel32.dll", CharSet = CharSet.Auto)]
    private static extern IntPtr GetModuleHandle(string? lpModuleName);

    private readonly Action                _callback;
    private readonly LowLevelKeyboardProc  _proc;   // GC anchor - must not be local variable
    private          IntPtr                _hook;

    internal HotkeyWindow(Action callback)
    {
        _callback = callback;
        _proc     = HookProc;                    // capture delegate before SetWindowsHookEx
        _hook     = SetWindowsHookEx(WH_KEYBOARD_LL, _proc, GetModuleHandle(null), 0);
        if (_hook == IntPtr.Zero)
        {
            int err = Marshal.GetLastWin32Error();
            TrayLog.Warn($"SetWindowsHookEx(WH_KEYBOARD_LL) failed (Win32 error {err})");
        }
        else
        {
            TrayLog.Info("WH_KEYBOARD_LL hook installed - Ctrl+Alt+V is active");
        }
    }

    internal bool IsRegistered => _hook != IntPtr.Zero;

    private IntPtr HookProc(int nCode, IntPtr wParam, IntPtr lParam)
    {
        if (nCode >= 0)
        {
            int msg = (int)wParam;
            if (msg == WM_KEYDOWN || msg == WM_SYSKEYDOWN)
            {
                var ks = Marshal.PtrToStructure<KBDLLHOOKSTRUCT>(lParam);

                if (ks.vkCode == VK_V)
                {
                    bool ctrl = (GetAsyncKeyState((int)VK_CONTROL) & 0x8000) != 0;
                    bool alt  = (GetAsyncKeyState((int)VK_MENU)    & 0x8000) != 0;
                    // Ignore injected events - SendCtrlV()'s own synthetic Ctrl+V
                    // must not re-trigger the hotkey.
                    bool inj  = (ks.flags & LLMHF_INJECTED) != 0;

                    if (!inj && ctrl && alt)
                    {
                        // Call directly - the callback must return quickly (spawn its own
                        // STA thread for clipboard/OLE work rather than doing it inline).
                        TrayLog.Info("[HOOK] Ctrl+Alt+V → invoking OTP callback");
                        _callback();
                        return (IntPtr)1; // suppress the original Ctrl+Alt+V keypress
                    }
                }
            }
        }
        return CallNextHookEx(_hook, nCode, wParam, lParam);
    }

    public void Dispose()
    {
        if (_hook != IntPtr.Zero)
        {
            UnhookWindowsHookEx(_hook);
            _hook = IntPtr.Zero;
        }
    }
}
