using System.Runtime.InteropServices;

namespace EasyUniVPN;

/// <summary>
/// Installs a WH_KEYBOARD_LL hook and matches configured quick-paste
/// shortcuts (one per university, e.g. "ctrl+alt+v" and "ctrl+shift+v").
///
/// Unlike RegisterHotKey (which fails when another app owns the combo) or
/// IMessageFilter (which depends on message routing to our hidden window),
/// a low-level keyboard hook is called by the kernel for every physical
/// keystroke, regardless of which application has focus or what privileges
/// the foreground process holds.
///
/// Shortcut matching is exact on the modifier set: "ctrl+alt+v" does not
/// fire while Shift is also held, so two shortcuts that share a key can
/// never both trigger. The hook is only installed when at least one binding
/// exists.
///
/// The hook is delivered on the installing thread via the message pump
/// (Application.Run() must be running on the same thread). The delegate is
/// stored in a field to prevent the GC from collecting it while the hook is
/// active - collecting the delegate causes an unrecoverable crash.
///
/// Callbacks are invoked directly from the hook proc on the UI thread.
/// They must return quickly - only do a fast check and spawn a background
/// STA thread for any heavy work (e.g. clipboard operations).
/// </summary>
internal sealed class HotkeyWindow : IDisposable
{
    private const int  WH_KEYBOARD_LL = 13;
    private const int  WM_KEYDOWN     = 0x0100;
    private const int  WM_SYSKEYDOWN  = 0x0104;
    private const uint LLMHF_INJECTED = 0x01;    // set on events generated by SendInput
    private const uint VK_CONTROL     = 0x11;
    private const uint VK_MENU        = 0x12;    // Alt
    private const uint VK_SHIFT       = 0x10;

    /// <summary>One parsed shortcut and the action it triggers.</summary>
    internal sealed class Binding
    {
        internal string Spec  = "";
        internal uint   Vk;
        internal bool   Ctrl, Shift, Alt;
        internal Action Callback = () => { };
    }

    /// <summary>
    /// Parses a canonical shortcut spec ("ctrl+alt+v": 1-3 of ctrl/shift/alt
    /// plus one letter, digit, or F1-F12) into a binding without a callback.
    /// Returns <c>null</c> when the spec is not usable.
    /// </summary>
    internal static Binding? TryParse(string spec)
    {
        if (string.IsNullOrWhiteSpace(spec))
            return null;
        var binding = new Binding { Spec = spec };
        foreach (string rawPart in spec.ToLowerInvariant().Split('+'))
        {
            string part = rawPart.Trim();
            switch (part)
            {
                case "ctrl":  binding.Ctrl  = true; break;
                case "shift": binding.Shift = true; break;
                case "alt":   binding.Alt   = true; break;
                default:
                    if (binding.Vk != 0) return null;   // more than one regular key
                    binding.Vk = KeyToVk(part);
                    if (binding.Vk == 0) return null;
                    break;
            }
        }
        bool anyModifier = binding.Ctrl || binding.Shift || binding.Alt;
        return binding.Vk != 0 && anyModifier ? binding : null;
    }

    private static uint KeyToVk(string key)
    {
        if (key.Length == 1)
        {
            char c = key[0];
            if (c >= 'a' && c <= 'z') return (uint)(0x41 + (c - 'a'));
            if (c >= '0' && c <= '9') return (uint)(0x30 + (c - '0'));
            return 0;
        }
        // f1-f12 → VK_F1 (0x70) onward.
        if (key.Length is 2 or 3 && key[0] == 'f'
            && int.TryParse(key.Substring(1), out int n) && n >= 1 && n <= 12)
            return (uint)(0x70 + n - 1);
        return 0;
    }

    private delegate IntPtr LowLevelKeyboardProc(int nCode, IntPtr wParam, IntPtr lParam);

    [DllImport("user32.dll",   SetLastError = true)]
    private static extern IntPtr SetWindowsHookEx(int idHook, LowLevelKeyboardProc lpfn, IntPtr hMod, uint dwThreadId);

    [DllImport("user32.dll",   SetLastError = true)]
    private static extern bool UnhookWindowsHookEx(IntPtr hhk);

    [DllImport("user32.dll")]
    private static extern IntPtr CallNextHookEx(IntPtr hhk, int nCode, IntPtr wParam, IntPtr lParam);

    [DllImport("user32.dll")]
    private static extern short GetAsyncKeyState(int vKey);

    [DllImport("kernel32.dll", CharSet = CharSet.Auto)]
    private static extern IntPtr GetModuleHandle(string? lpModuleName);

    [StructLayout(LayoutKind.Sequential)]
    private struct KBDLLHOOKSTRUCT
    {
        public uint    vkCode;
        public uint    scanCode;
        public uint    flags;
        public uint    time;
        public UIntPtr dwExtraInfo;
    }

    private readonly IReadOnlyList<Binding>  _bindings;
    private readonly LowLevelKeyboardProc?   _proc;   // GC anchor - must not be local variable
    private          IntPtr                  _hook;

    internal HotkeyWindow(IReadOnlyList<Binding> bindings)
    {
        _bindings = bindings;
        if (bindings.Count == 0)
        {
            TrayLog.Info("No quick-paste shortcuts configured - keyboard hook not installed");
            return;
        }
        _proc = HookProc;                        // capture delegate before SetWindowsHookEx
        _hook = SetWindowsHookEx(WH_KEYBOARD_LL, _proc, GetModuleHandle(null), 0);
        if (_hook == IntPtr.Zero)
        {
            int err = Marshal.GetLastWin32Error();
            TrayLog.Warn($"SetWindowsHookEx(WH_KEYBOARD_LL) failed (Win32 error {err})");
        }
        else
        {
            TrayLog.Info($"WH_KEYBOARD_LL hook installed - {bindings.Count} shortcut(s) active");
        }
    }

    /// <summary>True when shortcuts were requested and the hook is live.</summary>
    internal bool IsRegistered => _hook != IntPtr.Zero;

    private IntPtr HookProc(int nCode, IntPtr wParam, IntPtr lParam)
    {
        if (nCode >= 0)
        {
            int msg = (int)wParam;
            if (msg == WM_KEYDOWN || msg == WM_SYSKEYDOWN)
            {
                var ks = Marshal.PtrToStructure<KBDLLHOOKSTRUCT>(lParam);

                // Ignore injected events - the paste's own synthetic Ctrl+V
                // must not re-trigger a shortcut.
                if ((ks.flags & LLMHF_INJECTED) == 0)
                {
                    bool ctrl  = (GetAsyncKeyState((int)VK_CONTROL) & 0x8000) != 0;
                    bool shift = (GetAsyncKeyState((int)VK_SHIFT)   & 0x8000) != 0;
                    bool alt   = (GetAsyncKeyState((int)VK_MENU)    & 0x8000) != 0;

                    foreach (var binding in _bindings)
                    {
                        if (ks.vkCode != binding.Vk
                            || ctrl != binding.Ctrl || shift != binding.Shift || alt != binding.Alt)
                            continue;
                        // Call directly - the callback must return quickly (spawn its
                        // own STA thread for clipboard/OLE work rather than inline).
                        TrayLog.Info($"[HOOK] {binding.Spec} → invoking OTP callback");
                        binding.Callback();
                        return (IntPtr)1; // suppress the original keypress
                    }
                }
            }
        }
        return CallNextHookEx(_hook, nCode, wParam, lParam);
    }

    public void Dispose()
    {
        if (_hook != IntPtr.Zero)
        {
            UnhookWindowsHookEx(_hook);
            _hook = IntPtr.Zero;
        }
    }
}
